# Generated from reports/v1427_five_window_compact_tree_leaf2_tp14_2026-07-01.json and reports/v1427_tree_overlay_eval_2026-07-01.json.
# Do not edit by hand; regenerate from the replay artifacts when the candidate changes.

from __future__ import annotations

from typing import Any

V1427_FIVE_WINDOW_TREE_SOURCE = "reports/v1427_five_window_compact_tree_leaf2_tp14_2026-07-01.json"
V1427_OVERLAY_SOURCE = "reports/v1427_tree_overlay_eval_2026-07-01.json"

V1427_FIVE_WINDOW_TREE: dict[str, Any] = {'left': {'left': {'left': {'left': {'left': {'left': {'left': {'left': {'action': 'L_E0_TP8_SL6_T60_LOCK60_5_0',
                                                                         'n': 7},
                                                                'n': 13,
                                                                'right': {'action': 'S_E2_TP14_SL8_T90_LOCK90_6_0',
                                                                          'n': 6},
                                                                'split': ['pullback', 9.2405]},
                                                       'n': 26,
                                                       'right': {'left': {'action': 'S_E0_TP8_SL6_T60_LOCK60_5_0',
                                                                          'n': 2},
                                                                 'n': 13,
                                                                 'right': {'action': 'L_E0_TP14_SL8_T90_LOCK60_6_0',
                                                                           'n': 11},
                                                                 'split': ['rng15', 19.1205]},
                                                       'split': ['slope60', 1.7113]},
                                              'n': 29,
                                              'right': {'action': 'S_E0_TP14_SL8_T90_LOCK60_6_0', 'n': 3},
                                              'split': ['d30', 4.2844]},
                                     'n': 31,
                                     'right': {'action': 'L_E2_TP14_SL8_T90_LOCK90_6_0', 'n': 2},
                                     'split': ['vwap', -16.0165]},
                            'n': 49,
                            'right': {'left': {'action': 'L_E0_TP8_SL6_T60_LOCK60_5_0', 'n': 2},
                                      'n': 18,
                                      'right': {'left': {'left': {'left': {'action': 'S_E0_TP14_SL8_T90_LOCK60_6_0',
                                                                           'n': 3},
                                                                  'n': 5,
                                                                  'right': {'action': 'S_E0_TP14_SL8_T90_LOCK60_6_0',
                                                                            'n': 2},
                                                                  'split': ['slope60', -4.7785]},
                                                         'n': 12,
                                                         'right': {'left': {'action': 'L_E2_TP14_SL8_T90_LOCK90_6_0',
                                                                            'n': 3},
                                                                   'n': 7,
                                                                   'right': {'action': 'BASE', 'n': 4},
                                                                   'split': ['state_eq',
                                                                             'CNL-WPR-L:deep_discount_stable']},
                                                         'split': ['range_pos', 0.285]},
                                                'n': 16,
                                                'right': {'action': 'BASE', 'n': 4},
                                                'split': ['pullback', 22.1731]},
                                      'split': ['slope30', -6.5198]},
                            'split': ['adv3', 0.6392]},
                   'n': 73,
                   'right': {'left': {'left': {'action': 'S_E2_TP14_SL8_T90_LOCK90_6_0', 'n': 2},
                                      'n': 9,
                                      'right': {'left': {'left': {'action': 'L_E0_TP14_SL8_T90_LOCK60_6_0', 'n': 2},
                                                         'n': 4,
                                                         'right': {'action': 'L_E0_TP14_SL8_T90_LOCK60_6_0', 'n': 2},
                                                         'split': ['state_eq', 'CNL-WPR-L:deep_discount_stable']},
                                                'n': 7,
                                                'right': {'action': 'L_E2_TP12_SL8_T90_LOCK90_6_0', 'n': 3},
                                                'split': ['slope30', 1.3438]},
                                      'split': ['d30', 15.4591]},
                             'n': 24,
                             'right': {'left': {'left': {'action': 'BASE', 'n': 6},
                                                'n': 11,
                                                'right': {'left': {'action': 'L_E0_TP14_SL8_T90_LOCK60_6_0', 'n': 3},
                                                          'n': 5,
                                                          'right': {'action': 'BASE', 'n': 2},
                                                          'split': ['slope30', -0.2557]},
                                                'split': ['rng15', 25.6718]},
                                       'n': 15,
                                       'right': {'action': 'BASE', 'n': 4},
                                       'split': ['rsi', 55.9583]},
                             'split': ['rng15', 19.1205]},
                   'split': ['d30', 9.7433]},
          'n': 115,
          'right': {'left': {'left': {'left': {'action': 'BASE', 'n': 2},
                                      'n': 4,
                                      'right': {'action': 'BASE', 'n': 2},
                                      'split': ['state_eq', 'CNL-WPR-L:discount_mixed']},
                             'n': 27,
                             'right': {'left': {'left': {'action': 'L_E2_TP14_SL8_T90_LOCK90_6_0', 'n': 3},
                                                'n': 5,
                                                'right': {'action': 'L_E0_TP8_SL6_T60_LOCK60_5_0', 'n': 2},
                                                'split': ['adv3', 2.4773]},
                                       'n': 23,
                                       'right': {'left': {'left': {'action': 'L_E0_TP10_SL6_T90_LOCK60_5_0', 'n': 3},
                                                          'n': 10,
                                                          'right': {'left': {'action': 'S_E0_TP14_SL8_T90_LOCK60_6_0',
                                                                             'n': 3},
                                                                    'n': 7,
                                                                    'right': {'action': 'S_E2_TP12_SL8_T90_LOCK90_6_0',
                                                                              'n': 4},
                                                                    'split': ['state_eq', 'STUP-S:clean_extension']},
                                                          'split': ['state_eq', 'STUP-S:weak_chop']},
                                                 'n': 18,
                                                 'right': {'left': {'action': 'S_E0_TP14_SL8_T90_LOCK60_6_0', 'n': 4},
                                                           'n': 8,
                                                           'right': {'left': {'action': 'L_E2_TP14_SL8_T90_LOCK90_6_0',
                                                                              'n': 2},
                                                                     'n': 4,
                                                                     'right': {'action': 'S_E2_TP14_SL8_T90_LOCK90_6_0',
                                                                               'n': 2},
                                                                     'split': ['state_eq', 'CNL-WPR-L:discount_mixed']},
                                                           'split': ['state_eq', 'STUP-S:weak_chop']},
                                                 'split': ['rng15', 25.6718]},
                                       'split': ['pullback', 9.2405]},
                             'split': ['slope30', -3.8674]},
                    'n': 42,
                    'right': {'left': {'left': {'action': 'L_E2_TP6_SL4_T60', 'n': 3},
                                       'n': 8,
                                       'right': {'action': 'L_E0_TP14_SL8_T90_LOCK60_6_0', 'n': 5},
                                       'split': ['state_eq', 'STUP-S:weak_chop']},
                              'n': 15,
                              'right': {'left': {'action': 'S_E2_TP10_SL8_T90_LOCK90_6_0', 'n': 4},
                                        'n': 7,
                                        'right': {'action': 'L_E0_TP8_SL6_T60_LOCK60_5_0', 'n': 3},
                                        'split': ['slope30', 3.5071]},
                              'split': ['range_pos', 0.7407]},
                    'split': ['slope120', 4.9723]},
          'split': ['vwap', -5.3163]},
 'n': 230,
 'right': {'left': {'left': {'left': {'left': {'action': 'L_E0_TP8_SL6_T60_LOCK60_5_0', 'n': 3},
                                      'n': 12,
                                      'right': {'left': {'action': 'S_E0_TP14_SL8_T90_LOCK60_6_0', 'n': 3},
                                                'n': 9,
                                                'right': {'left': {'action': 'L_E2_TP12_SL8_T90_LOCK90_6_0', 'n': 3},
                                                          'n': 6,
                                                          'right': {'action': 'S_E0_TP14_SL8_T90_LOCK60_6_0', 'n': 3},
                                                          'split': ['vwap', -35.1889]},
                                                'split': ['rng15', 58.9042]},
                                      'split': ['state_eq', 'CNL-WPR-L:discount_mixed']},
                             'n': 30,
                             'right': {'left': {'action': 'L_E0_TP12_SL8_T90_LOCK60_6_0', 'n': 3},
                                       'n': 18,
                                       'right': {'left': {'left': {'action': 'L_E2_TP10_SL8_T90_LOCK90_6_0', 'n': 3},
                                                          'n': 13,
                                                          'right': {'left': {'action': 'BASE', 'n': 5},
                                                                    'n': 10,
                                                                    'right': {'action': 'L_E0_TP14_SL8_T90_LOCK60_6_0',
                                                                              'n': 5},
                                                                    'split': ['slope30', -2.4316]},
                                                          'split': ['slope30', -6.5198]},
                                                 'n': 15,
                                                 'right': {'action': 'S_E2_TP12_SL8_T90_LOCK90_6_0', 'n': 2},
                                                 'split': ['slope60', 1.7113]},
                                       'split': ['pullback', 15.8858]},
                             'split': ['slope60', -8.4958]},
                    'n': 50,
                    'right': {'left': {'left': {'left': {'action': 'L_E0_TP12_SL8_T90_LOCK60_6_0', 'n': 2},
                                                'n': 4,
                                                'right': {'action': 'BASE', 'n': 2},
                                                'split': ['state_eq', 'CNL-WPR-L:discount_mixed']},
                                       'n': 17,
                                       'right': {'left': {'left': {'action': 'S_E0_TP14_SL8_T90_LOCK60_6_0', 'n': 3},
                                                          'n': 5,
                                                          'right': {'action': 'BASE', 'n': 2},
                                                          'split': ['slope60', -2.4134]},
                                                 'n': 13,
                                                 'right': {'action': 'S_E0_TP14_SL8_T90_LOCK60_6_0', 'n': 8},
                                                 'split': ['range_pos', 0.1774]},
                                       'split': ['adv3', 0.6392]},
                              'n': 20,
                              'right': {'action': 'L_E0_TP10_SL6_T90_LOCK60_5_0', 'n': 3},
                              'split': ['slope30', 3.5071]},
                    'split': ['slope120', -4.7844]},
           'n': 115,
           'right': {'left': {'left': {'left': {'action': 'L_E0_TP8_SL6_T60_LOCK60_5_0', 'n': 3},
                                       'n': 11,
                                       'right': {'action': 'L_E0_TP14_SL8_T90_LOCK60_6_0', 'n': 8},
                                       'split': ['slope30', -3.8674]},
                              'n': 34,
                              'right': {'left': {'left': {'left': {'action': 'BASE', 'n': 3},
                                                          'n': 8,
                                                          'right': {'left': {'action': 'L_E2_TP8_SL6_T90', 'n': 2},
                                                                    'n': 5,
                                                                    'right': {'action': 'L_E2_TP8_SL6_T90', 'n': 3},
                                                                    'split': ['slope30', -0.2557]},
                                                          'split': ['slope120', 4.9723]},
                                                 'n': 14,
                                                 'right': {'left': {'action': 'S_E0_TP5_SL4_T45', 'n': 3},
                                                           'n': 6,
                                                           'right': {'action': 'L_E2_TP12_SL8_T90_LOCK90_6_0', 'n': 3},
                                                           'split': ['slope120', 7.7623]},
                                                 'split': ['rsi', 43.2912]},
                                        'n': 23,
                                        'right': {'left': {'action': 'S_E0_TP14_SL8_T90_LOCK60_6_0', 'n': 2},
                                                  'n': 9,
                                                  'right': {'left': {'left': {'action': 'BASE', 'n': 2},
                                                                     'n': 5,
                                                                     'right': {'action': 'L_E0_TP14_SL8_T90_LOCK60_6_0',
                                                                               'n': 3},
                                                                     'split': ['state_eq',
                                                                               'CNL-WPR-L:falling_discount_trap']},
                                                            'n': 7,
                                                            'right': {'action': 'S_E0_TP14_SL8_T90_LOCK60_6_0', 'n': 2},
                                                            'split': ['vwap', 27.6632]},
                                                  'split': ['vwap', -26.6274]},
                                        'split': ['slope30', 3.5071]},
                              'split': ['slope60', 0.444]},
                     'n': 65,
                     'right': {'left': {'left': {'left': {'action': 'L_E2_TP14_SL8_T90_LOCK90_6_0', 'n': 2},
                                                 'n': 4,
                                                 'right': {'action': 'S_E0_TP8_SL6_T60_LOCK60_5_0', 'n': 2},
                                                 'split': ['slope60', 4.6498]},
                                        'n': 6,
                                        'right': {'action': 'BLOCK', 'n': 2},
                                        'split': ['adv3', 10.6038]},
                               'n': 31,
                               'right': {'left': {'left': {'left': {'action': 'BASE', 'n': 2},
                                                           'n': 5,
                                                           'right': {'action': 'BASE', 'n': 3},
                                                           'split': ['state_eq',
                                                                     'CNL-WPR-L:falling_continuation_probe']},
                                                  'n': 11,
                                                  'right': {'left': {'action': 'S_E2_TP14_SL8_T90_LOCK90_6_0', 'n': 2},
                                                            'n': 6,
                                                            'right': {'left': {'action': 'BASE', 'n': 2},
                                                                      'n': 4,
                                                                      'right': {'action': 'S_E0_TP14_SL8_T90_LOCK60_6_0',
                                                                                'n': 2},
                                                                      'split': ['slope30', 5.7036]},
                                                            'split': ['slope30', -2.4316]},
                                                  'split': ['vwap', -5.3163]},
                                         'n': 25,
                                         'right': {'left': {'left': {'left': {'action': 'L_E0_TP10_SL6_T90_LOCK60_5_0',
                                                                              'n': 3},
                                                                     'n': 5,
                                                                     'right': {'action': 'BASE', 'n': 2},
                                                                     'split': ['pullback', 37.7176]},
                                                            'n': 10,
                                                            'right': {'left': {'action': 'S_E0_TP10_SL6_T90_LOCK60_5_0',
                                                                               'n': 2},
                                                                      'n': 5,
                                                                      'right': {'action': 'S_E2_TP14_SL8_T90_LOCK90_6_0',
                                                                                'n': 3},
                                                                      'split': ['rng15', 35.305]},
                                                            'split': ['range_pos', 0.7407]},
                                                   'n': 14,
                                                   'right': {'left': {'action': 'L_E0_TP14_SL8_T90_LOCK60_6_0', 'n': 2},
                                                             'n': 4,
                                                             'right': {'action': 'L_E0_TP14_SL8_T90_LOCK60_6_0',
                                                                       'n': 2},
                                                             'split': ['slope60', 9.376]},
                                                   'split': ['slope30', 5.7036]},
                                         'split': ['pullback', 18.8839]},
                               'split': ['state_eq', 'STUP-S:weak_chop']},
                     'split': ['rsi', 49.1795]},
           'split': ['slope120', 0.5593]},
 'split': ['rng15', 31.892]}

V1427_FIVE_WINDOW_TREE_BY_WINDOW: dict[str, dict[str, Any]] = {'2026-06-28': {'attempts': 86,
                'counts': {'BLOCKED_NO_TRADE': 2,
                           'MAX_HOLD_WIN': 1,
                           'NO_FILL': 26,
                           'SL': 2,
                           'TP': 1,
                           'TP1_FULL': 46,
                           'TP_BE': 3,
                           'TP_FULL': 4,
                           'entry_ttl_expired': 1},
                'filled': 57,
                'losses': 3,
                'net': 2.888922,
                'projected_50_filled': 33.14,
                'projected_50_net': 1.679606,
                'wins': 54,
                'wr': 0.9473684210526315},
 '2026-06-29': {'attempts': 82,
                'counts': {'BLOCKED_NO_TRADE': 3,
                           'NO_FILL': 7,
                           'SL': 3,
                           'TP1_FULL': 61,
                           'TP_BE': 2,
                           'TP_FULL': 4,
                           'TP_HOLD_MARK': 2},
                'filled': 72,
                'losses': 3,
                'net': 3.93731,
                'projected_50_filled': 43.9,
                'projected_50_net': 2.400799,
                'wins': 69,
                'wr': 0.9583333333333334},
 '2026-06-30': {'attempts': 30,
                'counts': {'HOLD_MARK': 1, 'NO_FILL': 9, 'SL': 4, 'TP1_FULL': 15, 'entry_ttl_expired': 1},
                'filled': 20,
                'losses': 4,
                'net': 0.755314,
                'projected_50_filled': 33.33,
                'projected_50_net': 1.258856,
                'wins': 16,
                'wr': 0.8},
 'v1422_live_fourth': {'attempts': 15,
                       'counts': {'NO_FILL': 5, 'TP1_FULL': 7, 'entry_ttl_expired': 3},
                       'filled': 7,
                       'losses': 0,
                       'net': 0.47,
                       'projected_50_filled': 23.33,
                       'projected_50_net': 1.566667,
                       'wins': 7,
                       'wr': 1.0},
 'v1426_live_fifth_current': {'attempts': 17,
                              'counts': {'BLOCKED_NO_TRADE': 1,
                                         'NO_FILL': 4,
                                         'SL': 1,
                                         'TP1_FULL': 10,
                                         'entry_ttl_expired': 1},
                              'filled': 11,
                              'losses': 1,
                              'net': 0.54,
                              'projected_50_filled': 32.35,
                              'projected_50_net': 1.588235,
                              'wins': 10,
                              'wr': 0.9090909090909091}}

V1427_FDT_RNG90_BLOCK_BY_WINDOW: dict[str, dict[str, Any]] = {'2026-06-28': {'attempts': 86,
                'counts': {'BLOCKED_NO_TRADE': 4,
                           'MAX_HOLD_WIN': 1,
                           'NO_FILL': 26,
                           'SL': 2,
                           'TP': 1,
                           'TP1_FULL': 45,
                           'TP_BE': 3,
                           'TP_FULL': 3,
                           'entry_ttl_expired': 1},
                'filled': 55,
                'losses': 3,
                'net': 2.777922,
                'projected_50_filled': 31.98,
                'projected_50_net': 1.615071,
                'wins': 52,
                'wr': 0.9454545454545454},
 '2026-06-29': {'attempts': 82,
                'counts': {'BLOCKED_NO_TRADE': 13,
                           'NO_FILL': 7,
                           'SL': 2,
                           'TP1_FULL': 53,
                           'TP_BE': 2,
                           'TP_FULL': 3,
                           'TP_HOLD_MARK': 2},
                'filled': 62,
                'losses': 2,
                'net': 3.48631,
                'projected_50_filled': 37.8,
                'projected_50_net': 2.125799,
                'wins': 60,
                'wr': 0.967741935483871},
 '2026-06-30': {'attempts': 30,
                'counts': {'BLOCKED_NO_TRADE': 1,
                           'HOLD_MARK': 1,
                           'NO_FILL': 9,
                           'SL': 3,
                           'TP1_FULL': 15,
                           'entry_ttl_expired': 1},
                'filled': 19,
                'losses': 3,
                'net': 0.805314,
                'projected_50_filled': 31.67,
                'projected_50_net': 1.34219,
                'wins': 16,
                'wr': 0.8421052631578947},
 'v1422_live_fourth': {'attempts': 15,
                       'counts': {'NO_FILL': 5, 'TP1_FULL': 7, 'entry_ttl_expired': 3},
                       'filled': 7,
                       'losses': 0,
                       'net': 0.47,
                       'projected_50_filled': 23.33,
                       'projected_50_net': 1.566667,
                       'wins': 7,
                       'wr': 1.0},
 'v1426_live_fifth_current': {'attempts': 17,
                              'counts': {'BLOCKED_NO_TRADE': 1,
                                         'NO_FILL': 4,
                                         'SL': 1,
                                         'TP1_FULL': 10,
                                         'entry_ttl_expired': 1},
                              'filled': 11,
                              'losses': 1,
                              'net': 0.54,
                              'projected_50_filled': 32.35,
                              'projected_50_net': 1.588235,
                              'wins': 10,
                              'wr': 0.9090909090909091}}
